- name: Get the join command from the master node
  delegate_to: master
  shell: kubeadm token create --print-join-command
  register: join_command
  run_once: true

#

- name: Join worker node to the cluster
  shell: "{{ join_command.stdout }}"
  args:
    chdir: /home/vagrant
#

- name: Reboot worker nodes
  reboot:
    msg: "Rebooting worker node after Kubernetes setup"
    reboot_timeout: 600
